### ISSUE TITLE
Some episodes are not downloading

### ISSUE THREAD

**Issue by limiteddi** [avipatilpro/Zee5-Stream-Scrapper#1]
For example `https://z5avi.herokuapp.com/?q=https://www.zee5.com/tvshows/details/adbhuture/0-6-628/adbhuture-episode-3-august-2-2017-full-episode/0-1-119100` returns 

`https:\/\/zee5vodnd.akamaized.nethttp:\/\/netst4z5x-vh.akamaihd.net\/i\/draco\/shows\/Zee_Bangla\/Adbhuture\/August\/02082017\/Adbhuture_Episode_3_Ozee.smil\/master.m3u8?hdnea=st=1610136321~exp=1610139321~acl=\/*~hmac=8eeba860cc8e4fd21c5b069c8faf04861d62e53c091a082c0f83ac2919b0c44e`

but the link returns either error or 403. Some other links work though.

**Comment by avipatilpro** [comment]
Use z5.movhdapp.ml

**Comment by limiteddi** [comment]
> Use https://z5.movhdapp.ml

is source code available if I wanted to put on linux server?

**Comment by avipatilpro** [comment]
> > Use https://z5.movhdapp.ml
> 
> is source code available if I wanted to put on linux server?

Yes, 
https://github.com/avipatilpro/ZEE5
